-- Seed drink_companies + drink_company_aliases from reviewed brewery/brand CSV.
-- Generated by: node scripts/seed_drink_companies.mjs --write-sql
-- Source CSV: /Users/askar/Documents/code/demo/no-menu-app/taplist-mobile/tools/product-pool-audit/brewery_brand_web_verified.csv
-- Generated at: 2026-06-30T17:18:55.730Z
--
-- Expected counts after run:
--   companies: 133
--   aliases:   47
--   pending review: 43
--   archived:       1
--
-- CSV -> table mapping (drink_companies):
--   canonical_group / verified_name_zh / source_name -> normalized_key (deduped group key, lowercased)
--   verified_name_zh                               -> canonical_name, display_name
--   verified_name_en                               -> canonical_name_en
--   verified_entity_type                           -> entity_type (cider_producer -> cidery)
--   verified_country + country_code                -> country, country_code
--   verified_city                                  -> origin_region
--   raw_country_values (+ city/country hints)        -> raw_country_values text[]
--   confidence                                     -> confidence
--   verification_status                            -> review_status
--   source_urls                                    -> source
--   verification_note / flags / review notes       -> source_note
--   operational_status = closed                    -> status = archived
--
-- CSV -> table mapping (drink_company_aliases):
--   source_name, original_candidate_zh/en, group variants -> alias
--   heuristic script label                               -> alias_language
--   variant kind                                         -> alias_type
--
-- Skipped CSV rows:
--   verification_status = data_issue
--   verified_entity_type = test_data
--   blank source/group/name rows
--
-- Idempotent: safe to re-run. normalized_key is not updated on conflict.

BEGIN;

INSERT INTO public.drink_companies (
  normalized_key,
  canonical_name,
  canonical_name_en,
  display_name,
  entity_type,
  country,
  country_code,
  origin_region,
  raw_country_values,
  confidence,
  review_status,
  source,
  source_note,
  status
)
VALUES
  ('艾尔复兴', '艾尔复兴', 'Re Ale Revival Brewing', '艾尔复兴', 'brewery_brand', 'United States', NULL, '美国', ARRAY['美国', 'United States']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified', 'active'),
  ('艾根伯格', '艾根伯格', 'Brauerei Schloss Eggenberg', '艾根伯格', 'brewery_brand', 'Austria', 'AT', 'Vorchdorf', ARRAY['奥地利', 'Vorchdorf']::text[], 'high', 'reviewed', 'https://www.schloss-eggenberg.at/en/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('everywhere', '艾薇儿', 'everywhere beer company', '艾薇儿', 'brewery_brand', 'United States', 'US', 'Orange, California', ARRAY['美国', 'Orange, California', 'United States']::text[], 'high', 'reviewed', 'https://www.everywherebeer.com/ | https://untappd.com/b/everywhere-little-egg/5738227', NULL, 'active'),
  ('艾英格', '艾英格', 'Ayinger Privatbrauerei', '艾英格', 'brewery_brand', 'Germany', 'DE', 'Aying', ARRAY['德国', 'Aying', 'Germany']::text[], 'high', 'reviewed', 'https://www.ayinger.de/index-en.html', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('巴伐利亚武僧', '巴伐利亚武僧', NULL, '巴伐利亚武僧', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('百得福', '百得福', 'Budweiser Budvar Brewery', '百得福', 'brewery_brand', 'Czech Republic', 'CZ', 'České Budějovice', ARRAY['捷克', 'České Budějovice', 'Czech Republic']::text[], 'high', 'reviewed', 'https://budweiserbudvar.com/brewery/ | https://www.budejovickybudvar.cz/en/home', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('班克斯', '班克斯', 'Banks Brewing', '班克斯', 'brewery_brand', 'Australia', 'AU', 'Seaford, Victoria', ARRAY['澳大利亚', 'Seaford, Victoria', 'Australia']::text[], 'medium', 'reviewed', 'https://www.banksbrewing.com.au/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('半颠', '半颠精酿', 'So Mad', '半颠精酿', 'brewery_brand', 'China', 'CN', '桂林', ARRAY['桂林']::text[], 'medium', 'reviewed', 'https://untappd.com/w/so-mad/392781', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('半吨', '半吨', NULL, '半吨', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('鼻行兽', '鼻行兽', 'Oozlefinch Beers & Blending', '鼻行兽', 'brewery_brand', 'United States', 'US', 'Hampton, Virginia', ARRAY['西安', 'Hampton, Virginia', 'China']::text[], 'medium', 'reviewed', 'https://oozlefinchbeers.com/', '由样例酒款及品牌匹配确认。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('比尔斯兄弟', '比尔斯兄弟', 'Bissell Brothers Brewing', '比尔斯兄弟', 'brewery_brand', 'United States', 'US', 'Portland, Maine', ARRAY['美国', 'Portland, Maine', 'United States']::text[], 'high', 'reviewed', 'https://bissellbrothers.com/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('彼岸酿造', '彼岸酿造', 'The Other Shore', '彼岸酿造', 'brewery_brand', 'China', 'CN', '乐山', ARRAY['乐山']::text[], 'medium', 'reviewed', 'https://untappd.com/b/the-other-shore/6689038', '英文名由酒款/酒厂页面交叉确认。 || 英文名由酒款/酒厂页面交叉确认。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('碧特博格', '碧特博格', 'Bitburger Brewery', '碧特博格', 'brewery_brand', 'Germany', 'DE', 'Bitburg', ARRAY['Bitburg']::text[], 'high', 'reviewed', 'https://www.bitburger-international.com/en/our-brands/bitburger/bitburger-brewery', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('布鲁瑞 / the bruery', '布鲁瑞', 'The Bruery', '布鲁瑞', 'brewery_brand', 'United States', 'US', 'Placentia, California', ARRAY['美国', 'Placentia, California', 'United States']::text[], 'high', 'reviewed', 'https://www.thebruery.com/pages/location-placentia', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('朝日', '朝日', 'Asahi', '朝日', 'brewery_brand', 'Japan', 'JP', '东京', ARRAY['日本', '东京', 'Japan']::text[], 'high', 'reviewed', 'https://www.asahibeer.co.jp/aboutus/summary/', '城市按公司总部填写。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('齿轮酿造', '齿轮精酿', 'Gear Craft Brewing', '齿轮精酿', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('赤耳酿造', '赤耳酿造', 'REDEARS BREWING', '赤耳酿造', 'brewery_brand', 'China', 'CN', '北京', ARRAY['北京', 'China']::text[], 'high', 'reviewed', 'https://www.bjbrew.com/exDetail.aspx?exid=98', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('赤屿谷盗', '赤屿谷盗', 'Grain Thief', '赤屿谷盗', 'brewery_brand', 'China', 'CN', '海南', ARRAY['海南', 'China']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '“依帕”是酒款；公开来源不足以确认官方英文名和具体城市，英文留空。 | partially_verified | english_unverified', 'active'),
  ('打嗝海狸', '打嗝海狸', 'Belching Beaver Brewery', '打嗝海狸', 'brewery_brand', 'United States', 'US', 'Oceanside, California', ARRAY['美国', 'Oceanside, California', 'United States']::text[], 'high', 'reviewed', 'https://belchingbeaver.com/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('凡人', '凡人', 'Mortalis Brewing', '凡人', 'brewery_brand', 'United States', 'US', 'Avon, New York', ARRAY['美国', 'Avon, New York', 'United States']::text[], 'medium', 'reviewed', 'https://www.mortalisbrewing.com/', '由 Persephone 等神话系列酒款确认。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('费登斯', '费登斯', 'Fidens Brewing', '费登斯', 'brewery_brand', 'United States', 'US', 'Albany, New York', ARRAY['美国', 'Albany, New York', 'United States']::text[], 'high', 'reviewed', 'https://fidensbrewing.com/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('分野酿造', '分野酿造', 'Quadrant Brewing', '分野酿造', 'brewery_brand', NULL, NULL, NULL, ARRAY['山东', 'China']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('风险酿造', '风险酿造', 'Venture Brewing', '风险酿造', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('疯熊工业', '疯熊工业', 'Crazy Bear Industries', '疯熊工业', 'brewery_brand', 'China', 'CN', '东莞', ARRAY['广州', '东莞', 'China']::text[], 'high', 'reviewed', 'https://crazybearindustry.com/', '品牌起源于广州海珠，2023 年自有酒厂建于东莞；城市按当前酒厂所在地填写。', 'active'),
  ('佛里蒙', '佛里蒙', 'Fremont Brewing', '佛里蒙', 'brewery_brand', 'United States', 'US', 'Seattle, Washington', ARRAY['美国', 'Seattle, Washington', 'United States']::text[], 'high', 'reviewed', 'https://www.fremontbrewing.com/contact-us', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('hoegaarden', '福佳', 'Hoegaarden', '福佳', 'brewery_brand', 'Belgium', 'BE', 'Hoegaarden', ARRAY['Hoegaarden']::text[], 'high', 'reviewed', 'https://hoegaarden.com/', '中文市场常用名为“福佳”。', 'active'),
  ('谷语者', '谷语者', NULL, '谷语者', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('哈德逊河谷', '哈德逊河谷', 'Hudson Valley Brewery', '哈德逊河谷', 'brewery_brand', 'United States', NULL, NULL, ARRAY['美国', 'United States']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified', 'active'),
  ('航标酿造', '航标酿造', NULL, '航标酿造', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('和弦', '和弦', NULL, '和弦', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('黑森林 / waldhaus', '黑森林', 'Privatbrauerei Waldhaus', '黑森林', 'brewery_brand', 'Germany', 'DE', 'Weilheim, Baden-Württemberg', ARRAY['德国', 'Weilheim, Baden-Württemberg', 'Germany']::text[], 'high', 'reviewed', 'https://www.waldhaus-bier.de/en/private-brewery/', 'Waldhaus 为正式品牌；“黑森林”为中文市场称呼。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('黑烟囱', '黑烟囱', 'BlackStack Brewing', '黑烟囱', 'brewery_brand', 'United States', 'US', 'Saint Paul, Minnesota', ARRAY['美国', 'Saint Paul, Minnesota', 'United States']::text[], 'high', 'reviewed', 'https://www.blackstackbrewing.com/ | https://untappd.com/b/blackstack-brewing-art-history/6614897', '样例 ART HISTORY 与 BlackStack 官方/平台记录一致。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('红男爵', '红男爵', NULL, '红男爵', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('狐朋酿造', '狐朋酿造', 'Hupeng Brewing', '狐朋酿造', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified', 'active'),
  ('蝴蝶结', '蝴蝶结', NULL, '蝴蝶结', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('花雅酿造', '花雅酿造', 'HARMO BREW', '花雅酿造', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('坏骨头', '坏骨头', 'Bad Bones Beer', '坏骨头', 'brewery_brand', 'Canada', 'CA', 'Dunham, Quebec', ARRAY['加拿大', 'Dunham, Quebec', 'Canada']::text[], 'high', 'reviewed', 'https://www.badbonesbeer.com/home-en | https://brewver.com/beers/1151069/Accident-Report', '样例 Accident Report 与 Bad Bones 对应。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('辉光', '辉光', 'Glow Brewing', '辉光', 'brewery_brand', NULL, NULL, NULL, ARRAY['美国', 'United States']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified', 'active'),
  ('回头客', '回头客', 'Frequentem Brewing', '回头客', 'brewery_brand', 'United States', 'US', 'Canandaigua, New York', ARRAY['美国', 'Canandaigua, New York', 'United States']::text[], 'high', 'reviewed', 'https://frequentembrewing.com/taplist/ | https://www.beeradvocate.com/beer/profile/60004/', '样例 Canandaigua Premium Lager 与 Frequentem 官方酒单对应。', 'active'),
  ('洄游造物', '洄游造物', 'WayfarerLab', '洄游造物', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('会饮酿造', '会饮酿造', NULL, '会饮酿造', 'brewery_brand', NULL, NULL, NULL, ARRAY['北京', 'China']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('佳卡哈', '佳卡哈', NULL, '佳卡哈', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('健力士', '健力士', 'Guinness', '健力士', 'brewery_brand', 'Ireland', 'IE', 'Dublin', ARRAY['Dublin', '爱尔兰']::text[], 'high', 'reviewed', 'https://www.guinness.com/en | https://www.guinness-storehouse.com/en', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('酒花民族', '酒花民族', 'Hop Nation Brewing', '酒花民族', 'brewery_brand', 'Australia', 'AU', 'Footscray, Melbourne', ARRAY['澳大利亚', 'Footscray, Melbourne', 'Australia']::text[], 'medium', 'reviewed', 'https://untappd.com/b/hop-nation-brewing-co-2026-fresh-hop-chop-ipa/6640918 | https://hopnation.com.au/', '中文市场名由同款酒对应关系确认；“酒花名族”为错别字。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('酒花农场', '酒花农场', 'Hops Farm', '酒花农场', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('郡区', '郡区', 'Parish Brewing', '郡区', 'brewery_brand', 'United States', 'US', 'Broussard, Louisiana', ARRAY['美国', 'Broussard, Louisiana', 'United States']::text[], 'high', 'reviewed', 'https://parishbeer.com/beer/reve/', '样例 Rêve Coffee Stout 明确属于 Parish Brewing；原中文“郡区”疑似把 Parish 直译为行政区。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('凯西', '凯西', 'Casey Brewing & Blending', '凯西', 'brewery_brand', 'United States', 'US', 'Glenwood Springs, Colorado', ARRAY['美国', 'Glenwood Springs, Colorado', 'United States']::text[], 'high', 'reviewed', 'https://caseybrewing.com/', NULL, 'active'),
  ('狸造', '狸造', NULL, '狸造', 'brewery_brand', NULL, NULL, NULL, ARRAY['北京', 'China']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('裂变酿造', '裂变酿造', 'Fission Brewing', '裂变酿造', 'brewery_brand', 'China', 'CN', '佛山', ARRAY['佛山', 'China']::text[], 'medium', 'reviewed', 'https://untappd.com/Fission_Brewing_Company', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('另一半', '另一半', 'Other Half Brewing', '另一半', 'brewery_brand', 'United States', 'US', 'Brooklyn, New York City', ARRAY['美国', 'Brooklyn, New York City', 'United States']::text[], 'high', 'reviewed', 'https://otherhalfbrewing.com/', '城市按品牌创立地及主要纽约酒厂填写。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('洛莱', '洛莱', 'Lolev Beer', '洛莱', 'brewery_brand', 'United States', 'US', 'Pittsburgh, Pennsylvania', ARRAY['美国', 'Pittsburgh, Pennsylvania', 'United States']::text[], 'high', 'reviewed', 'https://lolev.beer/beer/hyena | https://www.beermenus.com/breweries/34105-lolev-beer', '样例 Hyena、Jaguar、Arcole、Rubicon 等均与 Lolev Beer 对应。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('蔓延酿造', '蔓延酿造', 'Derive Brewery', '蔓延酿造', 'brewery_brand', 'China', 'CN', '武汉', ARRAY['武汉', 'China']::text[], 'high', 'reviewed', 'https://www.bjbrew.com/exDetail.aspx?exid=369 | https://untappd.com/DeriveBrewery', '原表 MANYAN Brewing 未获支持；公开资料使用 Derive Brewery。与美国 Derive Brewing Company 不是同一实体。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('矛盾体', '矛盾体', 'Equilibrium Brewery', '矛盾体', 'brewery_brand', 'United States', 'US', 'Middletown, New York', ARRAY['美国', 'Middletown, New York', 'United States']::text[], 'medium', 'reviewed', 'https://www.eqbrew.com/', '由样例 Radian、Fractal/命令行等产品系列交叉确认。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('美西', '美西啤酒', 'Wild West Brewing', '美西啤酒', 'brewery_brand', 'China', 'CN', '成都', ARRAY['成都', 'China']::text[], 'medium', 'reviewed', 'https://www.wildwestbrewing.cn/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('明日酿造', '明日酿造', 'Mingri Brewing', '明日酿造', 'brewery_brand', 'China', 'CN', '上海', ARRAY['上海', 'China']::text[], 'high', 'reviewed', 'https://untappd.com/v/mingri-brewing/9992037', NULL, 'active'),
  ('牛啤堂 / nbeer craft brewing', '牛啤堂', 'NBeer Craft Brewing', '牛啤堂', 'brewery_brand', NULL, NULL, NULL, ARRAY['北京', 'China']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('农舍山', '农舍山', 'Hill Farmstead Brewery', '农舍山', 'brewery_brand', 'United States', 'US', 'Greensboro Bend, Vermont', ARRAY['美国', 'Greensboro Bend, Vermont', 'United States']::text[], 'high', 'reviewed', 'https://hillfarmstead.com/visit-us/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('欧米尼珀罗', '欧米尼珀罗', 'Omnipollo', '欧米尼珀罗', 'brewery_brand', 'Sweden', 'SE', 'Stockholm', ARRAY['瑞典', 'Stockholm', 'Sweden']::text[], 'high', 'reviewed', 'https://omnipollo.com/', NULL, 'active'),
  ('澎湃家族', '澎湃家族', NULL, '澎湃家族', 'brewery_brand', NULL, NULL, NULL, ARRAY['比利时', 'Belgium']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('葡月圣树', '葡月圣树', 'Lua Brewing', '葡月圣树', 'brewery_brand', 'United States', 'US', 'Des Moines, Iowa', ARRAY['美国', 'Des Moines, Iowa', 'United States']::text[], 'high', 'reviewed', 'https://luabeer.com/des-moines-sherman-hill-lua-brewing-drink-menu | https://untappd.com/LuaBrewing/beer', 'Tulpa、Zen Scientist 等样例与 Lua Brewing 官方酒单一致。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('浦江半岛', '浦江半岛', NULL, '浦江半岛', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('撬啤酿造', '撬啤酿造', 'Qiao Beer Brewing', '撬啤酿造', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified', 'active'),
  ('倾斜谷仓', '倾斜谷仓', 'Tilted Barn Brewery', '倾斜谷仓', 'brewery_brand', 'United States', 'US', 'Exeter, Rhode Island', ARRAY['Exeter, Rhode Island']::text[], 'high', 'reviewed', 'https://www.tiltedbarnbrewery.com/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('撒切尔', '撒切尔', 'Thatchers Cider', '撒切尔', 'cidery', 'United Kingdom', 'GB', 'Sandford, Somerset', ARRAY['英国', 'Sandford, Somerset', 'United Kingdom']::text[], 'high', 'reviewed', 'https://www.thatcherscider.co.uk/', '属于苹果酒生产商，而非啤酒厂。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('塞拉多艾尔', '塞拉多艾尔', NULL, '塞拉多艾尔', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('三宝乐 / sapporo', '三宝乐', 'Sapporo Breweries', '三宝乐', 'brewery_brand', 'Japan', 'JP', '札幌', ARRAY['札幌']::text[], 'medium', 'reviewed', 'https://www.sapporobeer.jp/', '城市按品牌起源地填写；公司总部位于东京。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('三得利 / suntory', '三得利', 'Suntory', '三得利', 'brewery_brand', 'Japan', 'JP', '东京', ARRAY['东京']::text[], 'high', 'reviewed', 'https://www.suntory.com/', '城市按公司总部填写。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('三子酿造', '三子酿造', '3 Sons Brewing', '三子酿造', 'brewery_brand', 'United States', 'US', 'Dania Beach, Florida', ARRAY['美国', 'Dania Beach, Florida', 'United States']::text[], 'high', 'reviewed', 'https://www.3sonsbrewingco.com/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('僧侣', '僧侣', 'Monkish Brewing', '僧侣', 'brewery_brand', 'United States', 'US', 'Torrance', ARRAY['美国', 'Torrance', 'United States']::text[], 'high', 'reviewed', 'https://www.monkishbrewing.com/', '按主酒厂所在地填写。', 'active'),
  ('山乘酿造 / sheng craft beer', '山乘酿造', 'Sheng Craft Beer', '山乘酿造', 'brewery_brand', 'China', 'CN', '嵊州，绍兴', ARRAY['嵊州，绍兴']::text[], 'medium', 'reviewed', 'https://www.beertasting.com/en/brewery/sheng-craft-beer | https://www.instagram.com/p/CYQwj4PlvwN/', '公开资料确认创立并设厂于浙江绍兴嵊州；城市以县级市及地级市并列记录。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('山雀', '山雀', 'Mountain Finch', '山雀', 'brewery_brand', 'China', 'CN', '上海', ARRAY['上海', '上海嘉定', 'China']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '仅能由原始酒款与本地信息确认中文品牌和城市；未找到足够可靠的公开英文名，Mountain Finch 不写入验证值。 | partially_verified | english_unverified', 'active'),
  ('闪电萨拉玛', '闪电萨拉玛', NULL, '闪电萨拉玛', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('善良胡夫', '善良胡夫', 'Humble Forager Brewery', '善良胡夫', 'brewery_brand', 'United States', 'US', 'Waunakee, Wisconsin', ARRAY['美国', 'Waunakee, Wisconsin', 'United States']::text[], 'medium', 'reviewed', 'https://www.humbleforagerbrewery.com/', '中文名为中国市场常用译名。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('生命长河', '生命长河', 'Long Live Beerworks', '生命长河', 'brewery_brand', 'United States', 'US', 'Providence, Rhode Island', ARRAY['美国', 'Providence, Rhode Island', 'United States']::text[], 'medium', 'reviewed', 'https://longlivebeerworks.com/', '由 All Seeing Eye 等样例酒款确认。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('双尾酿造', '双尾酿造', 'Twin Tails Brewing', '双尾酿造', 'brewery_brand', 'China', 'CN', '苏州', ARRAY['苏州']::text[], 'high', 'reviewed', 'https://twintailsbrewing.com/ | https://untappd.com/Twin_Tails_', '官网及 Untappd 官方页面均确认英文名与苏州所在地。', 'active'),
  ('水猴子', '水猴子', 'Myth Monkey Beer', '水猴子', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('斯莫吉', '斯莫吉', 'Smooj', '斯莫吉', 'brewery_brand', 'United States', 'US', 'Ann Arbor, Michigan', ARRAY['Ann Arbor, Michigan']::text[], 'medium', 'reviewed', 'https://www.drinksmooj.com/ | https://untappd.com/troobado/beer', '“斯莫及/斯莫吉”均为音译；英文 Smooj 最可靠。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('虽吾酿造', '虽吾酿造', 'SUIWU BREWING', '虽吾酿造', 'brewery_brand', 'China', 'CN', '扬州', ARRAY['苏州', '扬州', 'China']::text[], 'high', 'reviewed', 'https://untappd.com/Suiwu_jennifer', '公开官方页面明确写明来自江苏扬州；“虽吴”为错别字。 || 公开官方页面明确写明来自江苏扬州；“虽吴”为错别字。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('索拉里斯', '索拉里斯', 'Solaris Beer & Blending', '索拉里斯', 'brewery_brand', 'United States', 'US', 'Murrieta, California', ARRAY['美国', 'Murrieta, California', 'United States']::text[], 'high', 'reviewed', 'https://solarisbeer.com/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('特纳亚溪', '特纳亚溪', 'Tenaya Creek Brewery', '特纳亚溪', 'brewery_brand', 'United States', 'US', 'Las Vegas, Nevada', ARRAY['Las Vegas, Nevada']::text[], 'high', 'reviewed', 'https://tenayacreek.com/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('天使之翼', '天使之翼', 'Wax Wings Brewing Co.', '天使之翼', 'brewery_brand', 'United States', 'US', 'Kalamazoo, Michigan', ARRAY['美国', 'Kalamazoo, Michigan', 'United States']::text[], 'high', 'reviewed', 'https://waxwingsbrewingco.square.site/ | https://www.beermenus.com/breweries/26904-wax-wings-brewing-company', 'Double Nazareth 等样例与 Wax Wings 对应。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('田园酿造', '田园酿造', NULL, '田园酿造', 'brewery_brand', NULL, NULL, NULL, ARRAY['云南', 'China']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('头脑冷静', '头脑冷静', 'CoolHead Brew', '头脑冷静', 'brewery_brand', '芬兰', 'FI', 'Helsinki', ARRAY['Helsinki']::text[], 'high', 'reviewed', 'https://coolhead.fi/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('退界', '退界', 'Tuijie', '退界', 'brewery_brand', 'China', 'CN', '成都', ARRAY['成都', 'China']::text[], 'medium', 'pending', 'https://www.460.net.cn/news/show-119016.html', '中文品牌与城市可确认；未找到足够可靠的官方英文名，因此英文留空。 | partially_verified | english_unverified', 'active'),
  ('weihenstephan', '唯森', 'Bayerische Staatsbrauerei Weihenstephan', '唯森', 'brewery_brand', 'Germany', 'DE', 'Freising', ARRAY['Freising']::text[], 'high', 'reviewed', 'https://www.weihenstephaner.de/en/', '中文市场也常见“维森/唯森”，英文官方名称最可靠。', 'active'),
  ('无毛用', '无毛用', NULL, '无毛用', 'brewery_brand', NULL, NULL, NULL, ARRAY['广州', 'China']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('五岔街', '五岔街', 'The Five Points Brewing Company', '五岔街', 'brewery_brand', 'United Kingdom', 'GB', 'London', ARRAY['英国', 'London', 'United Kingdom']::text[], 'medium', 'reviewed', 'https://fivepointsbrewing.co.uk/', '中文为市场译名。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('勿幕精酿', '勿幕精酿', 'WUMU Brewery', '勿幕精酿', 'brewery_brand', 'China', 'CN', '西安', ARRAY['西安', 'China']::text[], 'high', 'reviewed', 'https://untappd.com/w/wumu-craft-beer/383025/beer', NULL, 'active'),
  ('西澳山脊', '西澳山脊', 'Rocky Ridge Brewing', '西澳山脊', 'brewery_brand', 'Australia', 'AU', 'Jindong, Western Australia', ARRAY['澳大利亚', 'Jindong, Western Australia', 'Australia']::text[], 'medium', 'reviewed', 'https://rockyridgebrewing.com.au/', '由样例酒款与官方产品对应确认。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('犀首田园', '犀首田园', NULL, '犀首田园', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('香港啤酒公司', '香港啤酒公司', 'Hong Kong Beer Co.', '香港啤酒公司', 'brewery_brand', 'Hong Kong', 'HK', 'Hong Kong', ARRAY['香港', '中国香港', 'Hong Kong']::text[], 'high', 'reviewed', 'https://hkbeerco.com/', NULL, 'active'),
  ('小回酿造', '小回酿造', 'Turn Right Brewing', '小回酿造', 'brewery_brand', 'China', 'CN', '长春', ARRAY['长春']::text[], 'medium', 'reviewed', 'https://untappd.com/b/turn-right/6249390', '公开酒款页面确认 Turn Right（小回酿造）；所在地结合公开页面与原始所在地信息填写长春。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('邪恶双子', '邪恶双子', 'Evil Twin Brewing NYC', '邪恶双子', 'brewery_brand', 'United States', 'US', 'New York City', ARRAY['美国', 'New York City', 'United States']::text[], 'high', 'reviewed', 'https://eviltwin.nyc/', '城市按其纽约酒厂/品牌运营地填写。', 'active'),
  ('行匠 / trip smith', '行匠', 'TripSmith', '行匠', 'brewery_brand', 'China', 'CN', '贵阳', ARRAY['贵阳']::text[], 'high', 'reviewed', 'https://news.qq.com/rain/a/20250714A08L2E00 | https://www.douyin.com/user/MS4wLjABAAAASfrREJGZlgn0f01pYrNcT-yEBP3RbfA4Le7DxbVSq9b62WaumCz-71Ac2kzMljYE', '官方账号及贵阳官方媒体使用品牌拼写 TripSmith；原候选 Trip Smith 已纠正。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('行空', '行空', NULL, '行空', 'brewery_brand', NULL, NULL, NULL, ARRAY['青岛']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('兴业', '兴业', 'Industrial Arts Brewing Company', '兴业', 'brewery_brand', 'United States', 'US', 'Garnerville, New York', ARRAY['美国', 'Garnerville, New York', 'United States']::text[], 'medium', 'reviewed', 'https://industrialartsbrewing.com/', '由品牌中文译名及样例酒款匹配。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('修订', '修订', 'Revision Brewing Company', '修订', 'brewery_brand', 'United States', 'US', 'Sparks, Nevada', ARRAY['Sparks, Nevada']::text[], 'high', 'reviewed', 'https://revisionbrewing.com/locations/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('玄水屋', '玄水屋', 'SENSEVOL', '玄水屋', 'brewery_brand', 'China', 'CN', '西安', ARRAY['西安', 'China']::text[], 'medium', 'reviewed', 'https://untappd.com/w/sensevol/568713', 'Untappd 页面显示 SENSEVOL 玄水屋及西安所在地。', 'active'),
  ('鸭池', '鸭池', 'Duckpond Brewing', '鸭池', 'brewery_brand', 'Sweden', 'SE', 'Gothenburg', ARRAY['美国', '瑞典', 'Gothenburg']::text[], 'high', 'reviewed', 'https://www.instagram.com/duckpondbrewing/ | https://untappd.com/DuckpondBrewing', '原数据同时出现美国/瑞典；公开资料支持瑞典哥德堡。', 'active'),
  ('野鹅微醺', '野鹅微醺', 'YE BREWING', '野鹅微醺', 'brewery_brand', 'China', 'CN', '石家庄', ARRAY['石家庄']::text[], 'high', 'reviewed', 'https://www.yebrewing.com/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('一滴', '一滴', 'One Drop Brewing Co.', '一滴', 'brewery_brand', 'Australia', 'AU', 'Botany, New South Wales', ARRAY['新西兰', 'Botany, New South Wales', 'New Zealand']::text[], 'high', 'reviewed', 'https://www.onedropbrewingco.com.au/', '原表新西兰不正确；One Drop Brewing Co. 位于澳大利亚新南威尔士州。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('远山啤酒', '远山啤酒', 'Far Mont Beer', '远山啤酒', 'brewery_brand', 'China', 'CN', NULL, ARRAY[]::text[], 'medium', 'pending', 'https://untappd.com/w/far-mont-beer-e-a-a-e/599657', '中文、英文及国家可确认；城市没有可靠公开来源，留空。 | partially_verified | city_unverified | English name not found safely; fill from checked mapping or official source || 中文、英文及国家可确认；城市没有可靠公开来源，留空。 | partially_verified | city_unverified', 'active'),
  ('云酊', '云酊', NULL, '云酊', 'brewery_brand', NULL, NULL, NULL, ARRAY['云南', 'China']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('云朴精酿', '云朴精酿', 'YunPure Brewing', '云朴精酿', 'brewery_brand', 'China', 'CN', '昆明', ARRAY['昆明', 'China', '云南']::text[], 'high', 'reviewed', 'https://www.gokunming.com/cn/listings/item/34312/yunpure-brewery', '“云朵”为疑似录入/OCR 错误。', 'active'),
  ('长青工匠', '长青工匠', NULL, '长青工匠', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('纸飞机', '纸飞机', NULL, '纸飞机', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('智美 / chimay', '智美', 'Chimay', '智美', 'brewery_brand', 'Belgium', 'BE', 'Baileux (Chimay)', ARRAY['Baileux (Chimay)']::text[], 'high', 'reviewed', 'https://chimay.com/', 'English name not found safely; fill from checked mapping or official source', 'active'),
  ('种子', '种子', NULL, '种子', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified | English name not found safely; fill from checked mapping or official source', 'active'),
  ('左手巨人', '左手巨人', 'Left Handed Giant', '左手巨人', 'brewery_brand', 'United Kingdom', 'GB', 'Bristol', ARRAY['英国', 'Bristol', 'United Kingdom']::text[], 'high', 'reviewed', 'https://lefthandedgiant.com/', '不得与美国 Left Hand Brewing 混为一体。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('左手酿造 / left hand brewing', '左手酿造', 'Left Hand Brewing Company', '左手酿造', 'brewery_brand', 'United States', 'US', 'Longmont, Colorado', ARRAY['Longmont, Colorado']::text[], 'high', 'reviewed', 'https://lefthandbrewing.com/', '与英国 Left Handed Giant 不同。', 'active'),
  ('allagash brewing company', 'Allagash', 'Allagash Brewing Company', 'Allagash', 'brewery_brand', 'United States', 'US', 'Portland, Maine', ARRAY['Portland, Maine']::text[], 'high', 'reviewed', 'https://www.allagash.com/', NULL, 'active'),
  ('alus', 'Alus', 'Alus Brew Co.', 'Alus', 'brewery_brand', 'China', 'CN', '深圳', ARRAY['深圳', 'China']::text[], 'medium', 'pending', 'https://untappd.com/w/alus-brew-co/581964', '英文名与国家已确认；未找到足够可靠的城市来源，城市留空。 | partially_verified | city_unverified', 'active'),
  ('bell''s brewery', 'Bell''s', 'Bell''s Brewery', 'Bell''s', 'brewery_brand', 'United States', 'US', 'Comstock, Michigan', ARRAY['Comstock, Michigan']::text[], 'high', 'reviewed', 'https://bellsbeer.com/', NULL, 'active'),
  ('brasserie cantillon', 'Cantillon', 'Brasserie Cantillon', 'Cantillon', 'brewery_brand', 'Belgium', 'BE', 'Brussels', ARRAY['Brussels']::text[], 'high', 'reviewed', 'https://www.cantillon.be/', NULL, 'active'),
  ('cascade brewing', 'Cascade', 'Cascade Brewing', 'Cascade', 'brewery_brand', 'United States', 'US', 'Portland, Oregon', ARRAY['Portland, Oregon']::text[], 'high', 'reviewed', 'https://pdx.eater.com/2024/6/24/24185063/cascade-brewing-closes-portland-oregon-brewery', '已于 2024 年停止运营；名称与原所在地仍可确认。 | operational_status: closed', 'archived'),
  ('clag', 'CLAG', 'CLAG Brewing Company', 'CLAG', 'brewery_brand', 'United States', 'US', 'Sandusky, Ohio', ARRAY['美国', 'Sandusky, Ohio', 'United States']::text[], 'high', 'reviewed', 'https://www.clagbrewingco.com/', NULL, 'active'),
  ('deadman', 'Deadman', 'Deadman Brewery', 'Deadman', 'brewery_brand', 'Hong Kong', 'HK', 'Hong Kong', ARRAY['香港', 'Hong Kong']::text[], 'medium', 'reviewed', 'https://untappd.com/DeadManBrewery', NULL, 'active'),
  ('derive brewery', 'Derive Brewery', 'Derive Brewing Company', 'Derive Brewery', 'brewery_brand', 'United States', 'US', 'Columbus, Ohio', ARRAY['Columbus, Ohio']::text[], 'high', 'reviewed', 'https://www.derivebeer.com/', '该英文行按样例 LIMA 归入美国 Derive Brewing Company；不要与武汉蔓延酿造混并。', 'active'),
  ('e.t. brewery', 'E.T.', 'E.T. Brewery', 'E.T.', 'brewery_brand', 'China', 'CN', '深圳', ARRAY['深圳']::text[], 'medium', 'pending', 'brewery_brand_web_verified.csv', '可确认中国深圳活动/品牌关联；未找到稳定官方主页。 | partially_verified', 'active'),
  ('fever', 'FEVER', 'Fever Ales', 'FEVER', 'brewery_brand', 'China', 'CN', '西安', ARRAY['西安', 'China']::text[], 'high', 'reviewed', 'https://untappd.com/FeverAles | https://www.tengnian.com/brewery/50', '“想象中的雨”是其酒款，不是酒厂名。 || “想象中的雨”是其酒款，不是酒厂名。 | English name not found safely; fill from checked mapping or official source', 'active'),
  ('firestone walker brewing company', 'Firestone Walker', 'Firestone Walker Brewing Company', 'Firestone Walker', 'brewery_brand', 'United States', 'US', 'Paso Robles, California', ARRAY['Paso Robles, California']::text[], 'high', 'reviewed', 'https://www.firestonewalker.com/', NULL, 'active'),
  ('founders brewing co.', 'Founders', 'Founders Brewing Co.', 'Founders', 'brewery_brand', 'United States', 'US', 'Grand Rapids, Michigan', ARRAY['Grand Rapids, Michigan']::text[], 'high', 'reviewed', 'https://foundersbrewing.com/', NULL, 'active'),
  ('hesper', 'HESPER', 'HESPER', 'HESPER', 'brewery_brand', 'China', NULL, NULL, ARRAY['东莞', 'China']::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified', 'active'),
  ('ism brewing', 'ISM Brewing', 'ISM Brewing', 'ISM Brewing', 'brewery_brand', 'United States', 'US', 'Long Beach, California', ARRAY['Long Beach, California']::text[], 'high', 'reviewed', 'https://ism.beer/ | https://www.thewinecountry.com/ism-brewing-chepedelic-west-coast-ipa-16oz-can-lon.html', NULL, 'active'),
  ('jester king brewery', 'Jester King', 'Jester King Brewery', 'Jester King', 'brewery_brand', 'United States', 'US', 'Austin, Texas', ARRAY['Austin, Texas']::text[], 'high', 'reviewed', 'https://jesterkingbrewery.com/', NULL, 'active'),
  ('mojo', 'MOJO', 'MOJO', 'MOJO', 'brewery_brand', NULL, NULL, NULL, ARRAY[]::text[], 'low', 'pending', 'brewery_brand_web_verified.csv', '已进行名称及样例酒款检索，但未找到足以可靠确认中文名、英文名和城市/国家的公开来源；验证字段留空。 | unverified | english_unverified | city_unverified | country_unverified', 'active'),
  ('oskar blues brewery', 'Oskar Blues', 'Oskar Blues Brewery', 'Oskar Blues', 'brewery_brand', 'United States', 'US', 'Longmont, Colorado', ARRAY['Longmont, Colorado']::text[], 'high', 'reviewed', 'https://www.oskarblues.com/', '品牌起源于 Lyons，主要酒厂/总部按 Longmont 填写。', 'active'),
  ('shred', 'SHRED', 'Shred Beer Company', 'SHRED', 'brewery_brand', 'United States', 'US', 'Rocklin, California', ARRAY['美国', 'Rocklin, California', 'United States']::text[], 'high', 'reviewed', 'https://shredbeercompany.com/ | https://www.beeradvocate.com/beer/profile/65793/', NULL, 'active'),
  ('sierra nevada brewing co.', 'Sierra Nevada', 'Sierra Nevada Brewing Co.', 'Sierra Nevada', 'brewery_brand', 'United States', 'US', 'Chico, California', ARRAY['Chico, California']::text[], 'high', 'reviewed', 'https://sierranevada.com/', NULL, 'active'),
  ('stone brewing', 'Stone Brewing', 'Stone Brewing', 'Stone Brewing', 'brewery_brand', 'United States', 'US', 'Escondido, California', ARRAY['Escondido, California']::text[], 'high', 'reviewed', 'https://www.stonebrewing.com/', NULL, 'active'),
  ('tapstar', 'TAPSTAR', 'TAPSTAR', 'TAPSTAR', 'brewery_brand', 'China', 'CN', '贵阳', ARRAY['贵阳']::text[], 'medium', 'reviewed', 'https://m.36kr.com/p/3739743839879433 | https://www.xiaoyuzhoufm.com/episode/6684d2a953526fced0316cc3', '公开资料确认贵阳自酿品牌/酒吧；未发现稳定的正式中文名。', 'active'),
  ('tree house brewing company', 'Tree House', 'Tree House Brewing Company', 'Tree House', 'brewery_brand', 'United States', 'US', 'Charlton, Massachusetts', ARRAY['Charlton, Massachusetts']::text[], 'high', 'reviewed', 'https://treehousebrew.com/', '按主要酒厂/总部填写。', 'active'),
  ('trillium brewing company', 'Trillium', 'Trillium Brewing Company', 'Trillium', 'brewery_brand', 'United States', 'US', 'Canton, Massachusetts', ARRAY['Canton, Massachusetts']::text[], 'high', 'reviewed', 'https://trilliumbrewing.com/', '按主要生产酒厂填写。', 'active')
ON CONFLICT (normalized_key) DO UPDATE SET
  canonical_name = EXCLUDED.canonical_name,
  canonical_name_en = EXCLUDED.canonical_name_en,
  display_name = EXCLUDED.display_name,
  entity_type = EXCLUDED.entity_type,
  country = EXCLUDED.country,
  country_code = EXCLUDED.country_code,
  origin_region = EXCLUDED.origin_region,
  raw_country_values = EXCLUDED.raw_country_values,
  confidence = EXCLUDED.confidence,
  review_status = EXCLUDED.review_status,
  source = EXCLUDED.source,
  source_note = EXCLUDED.source_note,
  status = EXCLUDED.status,
  updated_at = now();


INSERT INTO public.drink_company_aliases (
  company_id,
  alias,
  alias_language,
  alias_type,
  source
)
SELECT
  c.id,
  v.alias,
  v.alias_language,
  v.alias_type,
  v.source
FROM (
  VALUES
  ('艾尔复兴', 'Ale Renaissance', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('everywhere', 'Everywhere', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('半颠', '半颠', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('彼岸酿造', 'Bian Brewing', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('彼岸酿造', '彼岸', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('齿轮酿造', '齿轮酿造', 'zh', 'name', 'brewery_brand_web_verified.csv'),
  ('赤耳酿造', '赤耳', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('赤屿谷盗', 'Chiyu Gudao', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('分野酿造', '分野', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('疯熊工业', '疯熊', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('疯熊工业', 'Crazy Bear', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('疯熊工业', 'Crazy Bear Industry', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('黑森林 / waldhaus', 'Waldhaus', 'en', 'name', 'brewery_brand_web_verified.csv'),
  ('回头客', 'Returning Guest', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('酒花民族', '酒花名族', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('酒花民族', 'Hop Nation Brewing Co.', 'en', 'translation', 'brewery_brand_web_verified.csv'),
  ('另一半', 'Other Half', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('美西', '美西', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('牛啤堂 / nbeer craft brewing', '牛皮堂', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('三宝乐 / sapporo', 'Sapporo', 'en', 'name', 'brewery_brand_web_verified.csv'),
  ('三子酿造', '三子', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('三子酿造', '3 Sons Brewing Co.', 'en', 'translation', 'brewery_brand_web_verified.csv'),
  ('僧侣', 'Monk Brewing', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('僧侣', 'Monkish', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('僧侣', 'Monkish Brewing', 'en', 'name', 'brewery_brand_web_verified.csv'),
  ('双尾酿造', 'Twin Tails', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('斯莫吉', '斯莫及', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('虽吾酿造', '虽吾', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('虽吾酿造', 'Suiwu', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('虽吾酿造', '虽吴', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('虽吾酿造', '虽吴酿造', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('weihenstephan', 'Weihenstephan', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('勿幕精酿', '勿幕', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('勿幕精酿', 'WUMUE Brewery', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('邪恶双子', 'Evil Twin Brewing', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('行匠 / trip smith', 'Trip Smith', 'en', 'name', 'brewery_brand_web_verified.csv'),
  ('玄水屋', 'Xuan Shui Wu', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('鸭池', 'Duckpond', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('野鹅微醺', 'Wild Goose Tipsy', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('野鹅微醺', '野鹅', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('远山啤酒', '远山', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('云朴精酿', 'Yunpu Craft', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('云朴精酿', '云朴', 'zh', 'source_value', 'brewery_brand_web_verified.csv'),
  ('云朴精酿', 'Yunpu', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('左手酿造 / left hand brewing', 'Left Hand', 'en', 'source_value', 'brewery_brand_web_verified.csv'),
  ('左手酿造 / left hand brewing', 'Left Hand Brewing', 'en', 'name', 'brewery_brand_web_verified.csv'),
  ('fever', '想象中的雨', 'zh', 'source_value', 'brewery_brand_web_verified.csv')
) AS v(normalized_key, alias, alias_language, alias_type, source)
JOIN public.drink_companies c
  ON c.normalized_key = v.normalized_key
ON CONFLICT (company_id, alias_normalized) DO UPDATE SET
  alias = EXCLUDED.alias,
  alias_language = EXCLUDED.alias_language,
  alias_type = EXCLUDED.alias_type,
  source = EXCLUDED.source;


COMMIT;

-- Post-run checks (run separately if desired):
-- SELECT count(*) FROM public.drink_companies;
-- SELECT count(*) FROM public.drink_company_aliases;
-- SELECT review_status, count(*) FROM public.drink_companies GROUP BY 1 ORDER BY 1;
-- SELECT normalized_key, display_name, country, review_status FROM public.drink_companies ORDER BY display_name;
-- SELECT a.alias, c.display_name, count(*) OVER (PARTITION BY a.alias_normalized) AS global_hits
-- FROM public.drink_company_aliases a
-- JOIN public.drink_companies c ON c.id = a.company_id
-- ORDER BY global_hits DESC, a.alias;
